<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
	<!ELEMENT biblioteca ( libro+ )>
		<!ELEMENT libro ( titulo, autor, anoPublicacion )>
			<!ELEMENT titulo ( #PCDATA )>
			<!ELEMENT autor ( #PCDATA )>
			<!ELEMENT anoPublicacion ( #PCDATA )>
]>

<biblioteca>
  <libro>
    <titulo>La vida está en otra parte</titulo>
    <autor>Milan Kundera</autor>
    <anoPublicacion>1973</anoPublicacion>
  </libro>
</biblioteca>
