=== DavidVieiro/XML/Ejercicio Listin Telefonico (David Vieiro Pazos)/listin.dtd
<!--
▪ Un nombre
▪ email (0 o varios)
▪ relacion (no obligatorio y vacío)
▪ Un identificador (id)
▪ Un atributo sexo (hombre o mujer) (no obligatorio)
▪ Atributos de relacion
	▪ amigo-de (indicará con qué otras personas del listin tiene relación) (una
	persona puede no tener relación con ninguna)
	▪ enemigo-de (indicará con qué otra persona del listin tiene enemistad)
	(una persona puede no tener enemistad con ninguna)
-->
<!ELEMENT listin ( persona+ )>
	<!ELEMENT persona ( nombre, email*, relacion )>
		<!ATTLIST persona
		id ID #REQUIRED
		sexo (hombre|mujer) #IMPLIED>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT relacion EMPTY>
		<!ATTLIST relacion
		amigo-de IDREFS #IMPLIED
		enemigo-de IDREFS #IMPLIED>

=== DavidVieiro/XML/Ejercicio Listin Telefonico (David Vieiro Pazos)/listin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "listin.dtd">

<listin>
	<persona id="ricky" sexo="hombre">
		<nombre>Ricky Martin</nombre>
		<email>ricky@puerto-rico.com</email>
		<email>ricky@gmail.com</email>
		<relacion amigo-de="leticia" />
	</persona>
	
	<persona id="leticia" sexo="mujer">
		<nombre>Leaticia Casta</nombre>
		<email>castal@micasa.com</email>
		<relacion />
	</persona>
	
	<persona id="pepe">
		<nombre>Pepe Pérez</nombre>
		<relacion amigo-de="leticia ricky" enemigo-de="pepe" />
	</persona>
	
	<persona id="ana">
		<nombre>Ana López</nombre>
		<relacion amigo-de="leticia pepe" enemigo-de="ricky" />
	</persona>
</listin>
